### ISSUE TITLE
Formatting isn't enforced

### ISSUE THREAD

**Issue by KangarooKoala** [robototes/ChargedUp2023#14]
When `check` is run on the CI, it formats the code. However, this does not affect the repository code (just the local copy for the CI).
As https://github.com/KangarooKoala/ChargedUp2023/pull/1 verified, the check passes despite the code having (and continuing to have) a formatting error (in that case an unused import).

**Comment by obj-obj** [comment]
@KangarooKoala the problem is that spotlessapply executes before spotless checks the formatting, I can just disable formatting when running `gradle check` to fix that
