### ISSUE TITLE
Fix issues in arm subsystem code

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/ChargedUp2023#61]
See comments on #52 
Key things are:
* Lots of dead code or constants should be removed to reduce confusion to people reading the code
* Arm feedforward is still broken. It's likely the values it's returning are now small enough that they don't matter. So you might try just deleting it entirely & just using PID. Only the middle position (0.415) would have a non-zero feedforward value, and that's close to the top so it would be pretty small.
* `isArmNearGoal()` uses a very loose definition of 'near', which is great for the `SetFullArmCommand` (as it can start moving the wrist before the arm is actually at its goal) but bad for autonomous (as the arm is about 30 degrees short of the goal when the auto code moves on to the next thing).

**Comment by jbko6** [comment]
In our testing of auto today, using the current version of isArmNearGoal was still useful for auto. I definitely agree that the "near" value should be defined (or passed through as an argument), but you can kinda see the benefit of a large tolerance in the auto here: https://photos.app.goo.gl/wMgYEezFxzacG3Xs7
It speeds up the placing of the piece quite a bit as wrist is in place before arm is done moving

**Comment by TAKBS2412** [comment]
For the `isArmNearGoal()` issue it would be good to have a way of tracking the dynamic constraints of the wrist (e.g., not running into the ground) and planning around those accordingly (in our case, likely waiting until the arm is at an angle where moving the wrist won't damage it).

Fortunately, we only have 2 DOFs to worry about, so these constraints won't be as complicated other teams with 3+ DOFs will run into (although I can still imagine this being difficult).

**Comment by jamesdooley4** [comment]
> In our testing of auto today, using the current version of isArmNearGoal was still useful for auto. I definitely agree that the "near" value should be defined (or passed through as an argument), but you can kinda see the benefit of a large tolerance in the auto here: https://photos.app.goo.gl/wMgYEezFxzacG3Xs7 It speeds up the placing of the piece quite a bit as wrist is in place before arm is done moving
I like the idea of passing in a value that defines "near" for the use case, so the autonomous routine can use that to control when the wrist moves (or something else happens).
