### ISSUE TITLE
Run automated test in CI, similar to last year

### ISSUE THREAD

**Issue by TAKBS2412** [robototes/ChargedUp2023#9]
Last year we had an automated test which ensured there wasn't a crash on startup, in autonomous, or when disabled. Having that again would be useful, especially at this stage when the project hasn't stabilized yet.

PR for reference:  https://github.com/robototes/RapidReact2022/pull/43

**Comment by obj-obj** [comment]
The stuff for that is in the CI config file, it's just commented out right now until we can write the java code
